from dataclasses import dataclass
from typing import List, Dict, Any

@dataclass
class ScenarioFixedPoint:
    """Base class representing a formally defined Fixed Point."""
    category: str
    sub_type: str
    dsl_code: str
    inferred_params: Dict[str, Any]
    reasoning: str

def parse_fixed_points(fp_list: List[Dict[str, Any]]) -> List[ScenarioFixedPoint]:
    """
    Converts the LLM's JSON output into a list of ScenarioFixedPoint objects.
    These objects act as the "Test Oracles" and "Optimization Objectives" for the Fuzzer.
    """
    parsed_objects = []
    
    for fp_data in fp_list:
        # Basic validation to ensure the LLM strictly followed the DSL
        dsl_code = fp_data.get("dsl_formalization", "")
        if "INVARIANT_ALWAYS" not in dsl_code and "ON_EVENT" not in dsl_code:
            raise ValueError(f"Invalid DSL syntax generated by LLM: {dsl_code}")
            
        parsed_obj = ScenarioFixedPoint(
            category=fp_data.get("category"),
            sub_type=fp_data.get("sub_type"),
            dsl_code=dsl_code,
            inferred_params=fp_data.get("inferred_parameters", {}).get("values", {}),
            reasoning=fp_data.get("inferred_parameters", {}).get("description", "")
        )
        parsed_objects.append(parsed_obj)
        
    return parsed_objects
